version: '3'
services:
  postgres:
    container_name: 'postgres_dev'
    env_file: ./env/psql.env
    restart: always
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
volumes:
  psql_data:
